### ISSUE TITLE
global `ActionMap` caching / completion initialization

### ISSUE THREAD

**Issue by blaggacao** [rsteube/carapace#532] opened 2022-05-26 01:49 UTC
I have a json that holds all the information necessary to compose completion. Launching the command that generates that json takes up to 3 seconds in extreme cases (yeah, bad).

```json
[{"cell":"std","organelles":[{"clade":"runnables","organelle":"cli","readme":"/nix/store/0v43f20l1n9i2gcwrx7k7aab2wfz9qlg-cells/std/cli/Readme.md","targets":[{"actions":[{"description":"exec this target","name":"run"}],"deps":[],"description":"A tui for projects that conform to Standard","name":"default","readme":"/nix/store/0v43f20l1n9i2gcwrx7k7aab2wfz9qlg-cells/std/cli/default.md"}]},{"clade":"functions","organelle":"lib","readme":"/nix/store/0v43f20l1n9i2gcwrx7k7aab2wfz9qlg-cells/std/lib/Readme.md","targets":[{"actions":[],"deps":[],"description":"n/a","name":"fromMakesWith","readme":"/nix/store/0v43f20l1n9i2gcwrx7k7aab2wfz9qlg-cells/std/lib/fromMakesWith.md"},{"actions":[],"deps":[],"description":"n/a","name":"mkShell","readme":""}]},{"clade":"functions","organelle":"devshellProfiles","readme":"/nix/store/0v43f20l1n9i2gcwrx7k7aab2wfz9qlg-cells/std/devshellProfiles/Readme.md","targets":[{"actions":[],"deps":[],"description":"n/a","namestd/devshellProfiles/default.md"}]},{"clade":"devshells","organelle":"devshells","readme":"","targets":[{"actions":[{"description":"enter this devshell","name":"enter"}],"deps":[],"description":"n/a","name":"default","readme":""}]},{}],"readme":"/nix/store/0v43f20l1n9i2gcwrx7k7aab2wfz9qlg-cells/std/Readme.md"}]
```

After transforming this into an `ActionMap` of  `carapace.ActionValues()` I want to cache the entire `ActionMap` for ~30 sec, so that subsequent completions during the same completion "session" don't take 3 seconds each.

What can I do?

**Comment by blaggacao** [comment] 2022-05-26 01:55
Here is a little more context with dummy `carapace.ActionValues()` per branch.
Essentially I can't afford to cache the leaves, individually, but must cache the entire tree upfront.

```go
func init() {
	// completes: '//cell/organelle/target:action'
	carapace.Gen(rootCmd).PositionalAnyCompletion(
		carapace.ActionMultiParts("//", func(cPrefix carapace.Context) carapace.Action {
			switch len(cPrefix.Parts) {
			case 0:
				return carapace.ActionValues()
			default:
				return carapace.ActionMultiParts("/", func(c carapace.Context) carapace.Action {
					fmt.Printf("%v", c.Parts)
					switch len(c.Parts) {
					// cell
					case 0:
						return carapace.ActionValues("aa", "bb").Invoke(c).Filter(c.Parts).Suffix("/").ToA()
					// organelle
					case 1:
						// return ActionTargets().Invoke(c).Filter(c.Parts).Suffix("/").ToA()
						return carapace.ActionValues("cc", "dd").Invoke(c).Filter(c.Parts).Suffix("/").ToA()
					// target & action
					case 2:
						// return ActionTargets().Invoke(c).Filter(c.Parts).Suffix("/").ToA()
						return carapace.ActionMultiParts(":", func(cTarget carapace.Context) carapace.Action {
							switch len(cTarget.Parts) {
							// target
							case 0:
								return carapace.ActionValues("ee", "ff").Invoke(c).Filter(c.Parts).Suffix(":").ToA()
							// action
							case 1:
								return carapace.ActionValues("gg", "hh").Invoke(c).Filter(c.Parts).ToA()
							default:
								return carapace.ActionValues()
							}
						}).Invoke(c).ToA()
					default:
						return carapace.ActionValues()
					}
				}).Invoke(cPrefix).ToA()
			}
		}).Cache(30 * time.Second),
	)
}
```

**Comment by rsteube** [comment] 2022-05-26 09:00
Still wrapping my head around this, but you might get away with something like this:
```go
carapace.ActionCallback(func(c carapace.Context) carapace.Action {
	return carapace.ActionValuesDescribed(
		"//std/cli/default", "A tui for projects that conform to Standard",
		"//std/cli/default:run", "exec this target",
		"//std/lib/fromMakesWith", "",
		"//std/lib/mkShell", "",
		"//std/devshells/default", "",
		"//std/devshells/default:enter", "enter this devshell",
	).Cache(30 * time.Second).Invoke(c).ToMultiPartsA("/").Invoke(c).ToMultiPartsA(":")
})
```
The issue with setting a cache on `ActionMultiParts` is that the [RawValues](https://github.com/rsteube/carapace/blob/master/action.go#L15) (which are being cached) are already altered and all you would do is cache the current segment (e.g. values below `//std/cli/`) and break completion for other segments (getting completion for `//std/cli/` although current word is `//std/lib/`).

Individual caching should be possible as well but each action would need to be invoked explicitly so that the cache is actually written on the first load.
Altenative would be to do custom caching of the generated `json` separately,

**Comment by blaggacao** [comment] 2022-05-26 17:09
Hm, this looks _somewhat_ going in the right direction:

```console
cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _


cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //
//std/

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std
//std/

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/
 //std/cli/
//std/lib/
//std/devshells/

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/li
//std/lib/

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/lib
//std/lib/

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/lib/
 //std/lib/fromMakesWith
//std/lib/mkShell

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cl
//std/cli/

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/
//std/cli/default

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/de
//std/cli/default

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/default
 //std/cli/default (A tui for projects that conform to Standard)
//std/cli/default:

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/default:
//std/cli/default:run

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/default:run
//std/cli/default:run
```

**Comment by blaggacao** [comment] 2022-05-26 17:15
_Actually_, after reducing a little to:

```go
		carapace.ActionCallback(func(c carapace.Context) carapace.Action {
			return carapace.ActionValuesDescribed(
				"//std/cli/default:run", "exec this target: A tui for projects that conform to Standard",
				"//std/devshells/default:enter", "enter this devshell",
			).Cache(30 * time.Second).Invoke(c).ToMultiPartsA("/").Invoke(c).ToMultiPartsA(":")
		}),
```


this looks pretty good:
```console
cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std
//std/

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/
 //std/cli/
//std/devshells/

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/
//std/cli/default:

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/default:
//std/cli/default:run

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/default:run
//std/cli/default:run
```

I wonder, though if it's ok that in a multipart the entire string is shown or whether it should actually only be the last part?

**Comment by rsteube** [comment] 2022-05-26 17:23
Hmm.. no shouldn't be that way. Bash has no concept of display values, but i am using a trick to enable that.
Should only be the last part unless there is only one value as that will be inserted.

**Comment by blaggacao** [comment] 2022-05-26 17:29
#533 seems to work fine:

```go
		carapace.ActionCallback(func(c carapace.Context) carapace.Action {
			return carapace.ActionValuesDescribed(
				"//std/cli/default:run", "exec this target: A tui for projects that conform to Standard",
				"//std/devshells/default:enter", "enter this devshell",
			).Cache(30*time.Second).Invoke(c).ToMultiPartsA("/", ":")
		}),
```
except for the issue of showing the entire string:
```console
cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go mod vendor
go: downloading github.com/rsteube/carapace v0.20.4-0.20220526092656-c9b358dda0b0

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure took 11s
❯ go run . _carapace bash _ //std/cli
//std/cli/

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/
//std/cli/default:

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/default
//std/cli/default:

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/default:
//std/cli/default:run

cells/std/cli on  main [$!+] via 🐹 v1.17.9 via ❄️  impure
❯ go run . _carapace bash _ //std/cli/default:run
//std/cli/default:run
```

**Comment by blaggacao** [comment] 2022-05-26 17:31
If you want to test:

https://github.com/divnix/std/tree/imp/cli-completion

```
cd cells/std/cli
go mod vendor
go run . _carapace bash _ //std/cli/
```

**Comment by rsteube** [comment] 2022-05-26 17:44
Thx. Should be caused by [this](https://github.com/rsteube/carapace/blob/master/invokedAction.go#L104) though. It overwrites the display value with the field split by the current delimiter disregarding any previous delimiter (which it doesn't know of).
Should probably work by splitting the current display value (which was altered) by the delimiter so that previous changes don't get lost.

**Comment by blaggacao** [comment] 2022-05-26 17:47
I did understand 50% :smile:. Do you expect me to submit a patch or would you want to give it a try yourself?

**Comment by rsteube** [comment] 2022-05-26 17:53
Yeah, sorry it's a bit more complicated than i thought. Will look at it myself :laughing: .

**Closed** 2022-05-27 13:12 UTC
